version: 2.1

orbs:
  ruby: circleci/ruby@1.3

jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: '1.17.2'
          with-cache: false
      - run:
          name: Build CI
          command: bundle exec rake ci

workflows:
  build_and_test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ['3.1', '3.0', '2.7']

